# numpy ndarray 이해하기
 
numpy는 특히 벡터 및 행렬 연산에 있어 편의성을 제공하는 라이브러리로, 앞으로 사용하게 될 pandas와 시각화 표현에 기반이 되는 라이브러리라고 할 수 있다.
 
numpy에서는 기본적으로 array(어레이)라는 단위로 데이터를 관리하고, 이에 대한 연산을 수행하게 된다. 

In [1]:
import numpy as np

# 1차원 array

In [3]:
data = [6,7.5,8,0,1]

In [4]:
data

[6, 7.5, 8, 0, 1]

In [5]:
arr1 = np.array(data)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
arr1.shape

(5,)

In [7]:
arr = np.array([2,3,4])
arr

array([2, 3, 4])

# 2차원 array

In [8]:
data2 = [[1,2,3,4], [5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

# zeros(), ones(), arange() 함수 기능

In [11]:
# 0으로 된 array 만들기
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 데이터 타입

**numpy에서 사용 가능한 데이터형(dtype) 정리**
 
** - int8, int16, int32, int64** : 부호가 있는 [8, 16, 32, 64]비트 정수 

** - uint8, uint16, uint32, uint64** : 부호가 없는 [8, 16, 32, 64]비트 정수 

** - float16, float32, float64, float128** :[16, 32, 64, 128]비트 실수 

** - complex64, complex128, complex256** : [64, 128, 256]비트 복소수 

** - bool** : 불리언 (True 또는 False) 

** - object **: Python 오브젝트 형 

** - string_** : 문자열 

** - unicode_ **: 유니코드 문자열 

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
# 기존의 타입을 변경 <-- astype()
float_arr = arr.astype(np.float64)
float_arr

array([2., 3., 4.])

In [17]:
float_arr.dtype

dtype('float64')

## array 관련 연산
 
두 array 간에는 더하기, 빼기, 곱하기, 나누기 등의 연산을 수행할 수 있다. '+', '-', '*', '/' 등과 같이 일반 숫자에 대해 사용하는 연산자를 사용하면 된다.
 
이 떄, 이러한 더하기, 빼기, 곱하기, 나누기 등의 연산은 두 array 상의 동일한 위치의 성분끼리 이루어지게 되므로, 당연히 두 array의 모양이 같아야 계산이 가능하다.
 
하나의 array와 일반 숫자 간에 연산을 하는 것도 가능한데, 이 경우 해당 숫자와 array 내 모든 성분 간에 해당 연산이 이루어지게 된다.

In [18]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
arr2 = np.array([[7,8,9], [10,11,12]], dtype=np.float64)

In [19]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [21]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [22]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [23]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

# array 인덱싱

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5]

np.int64(5)

In [27]:
arr[5:8]

array([5, 6, 7])

In [28]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

# 2차원 array

In [30]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
# 2행의 전체값 가져오기
arr2[2, :]

array([ 9, 10, 11, 12])

In [32]:
# 1행 ~2행의 전체값 가져오기
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# 전체 행을 가져오되, 마지막 열 값만 가져오기
arr2[:,3]   # 마지막 열 표현은 -1도 가능

array([ 4,  8, 12, 16])

In [34]:
#0~1행까지 1~2열까지의 값만 가오기
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

# 불리언 인덱싱

In [35]:
names = np.array(['ccc', 'hhh', 'bbb', 'ccc', 'bbb', 'hhh', 'ccc'])
data = np.random.randn(7,4)
                  
                  

In [36]:
names

array(['ccc', 'hhh', 'bbb', 'ccc', 'bbb', 'hhh', 'ccc'], dtype='<U3')

In [37]:
data

array([[ 0.15584109, -1.08832809,  0.48552374,  0.42404367],
       [ 0.74134988,  0.54805794, -0.2168103 ,  1.06626988],
       [-0.11269753,  0.23983369, -0.28858399, -0.3512561 ],
       [-0.22930174,  1.05206985, -1.17258342,  0.55340531],
       [-0.99974345, -1.31870511, -1.49850107,  0.61974996],
       [ 0.62740971, -0.24533419,  1.15189449, -1.72626108],
       [ 0.2833744 ,  0.8799978 , -0.36462145,  0.90838729]])

In [40]:
names  == 'ccc'

array([ True, False, False,  True, False, False,  True])

In [41]:
data[names == 'ccc', :]

array([[ 0.15584109, -1.08832809,  0.48552374,  0.42404367],
       [-0.22930174,  1.05206985, -1.17258342,  0.55340531],
       [ 0.2833744 ,  0.8799978 , -0.36462145,  0.90838729]])

In [ ]:
data[{names = 'ccc') | 